// <auto-generated />
using System;
using Mango.Services.CouponAPI.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231002061807_SeedDataToCouponDB")]
    partial class SeedDataToCouponDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-rc.1.23419.6");

            modelBuilder.Entity("Mango.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<Guid>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("REAL");

                    b.Property<int>("MinAmount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = new Guid("aa66e99a-80c6-4278-b792-52889b13dd72"),
                            CouponCode = "10OFF",
                            CreatedAt = new DateTime(2023, 10, 2, 11, 48, 7, 67, DateTimeKind.Local).AddTicks(3592),
                            DiscountAmount = 10.0,
                            MinAmount = 20,
                            UpdatedAt = new DateTime(2023, 10, 2, 11, 48, 7, 67, DateTimeKind.Local).AddTicks(3603)
                        },
                        new
                        {
                            CouponId = new Guid("3c176427-f790-4315-bf86-32bbcb3c5a71"),
                            CouponCode = "20OFF",
                            CreatedAt = new DateTime(2023, 10, 2, 11, 48, 7, 67, DateTimeKind.Local).AddTicks(3665),
                            DiscountAmount = 20.0,
                            MinAmount = 40,
                            UpdatedAt = new DateTime(2023, 10, 2, 11, 48, 7, 67, DateTimeKind.Local).AddTicks(3665)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
